repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ '--pytest-test-first' ]
      - id: no-commit-to-branch
        args: [ --branch, main ]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: ruff check
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]
