[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
addopts = [
  "--tb=short",
  "--fail-on-template-vars",
]
norecursedirs = ["media", "venv", "node_modules", ".direnv", ".git"]

[tool.ruff]
target-version = "py311"

line-length = 120

select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "S", # flake8-bandit
    "D", # pydocstyle
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "C", # flake8-comprehensions
]

ignore = [
  "D1", # Missing docstrings

]

[tool.ruff.per-file-ignores]
"*/tests/**/test_*.py" = [
    "S",
]
"*/baker_recipes.py" = [
    "S",
]

[tool.ruff.isort]
combine-as-imports=true
split-on-trailing-comma=true
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder"]
force-wrap-aliases=true

[tool.ruff.isort.sections]
django = ["django"]

[tool.ruff.pydocstyle]
convention = "google"
